html/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'shop', 'as' => 'shop.'], function() {
    Route::get('index', 'ShopController@index')->name('index');
    Route::get('c/{taxonomyName}/{taxon}', 'ShopController@category')->name('category');
    Route::get('p/{product}', 'ShopController@product')->name('product');
});

Route::group(['prefix' => 'cart', 'as' => 'cart.'], function() {
    Route::get('show', 'CartController@show')->name('show');
    Route::post('add/{product}', 'CartController@add')->name('add');
    Route::post('update/{cart_item}', 'CartController@update')->name('update');
    Route::post('remove/{cart_item}', 'CartController@remove')->name('remove');
});

Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], function() {
    Route::get('show', 'CheckoutController@show')->name('show');
    Route::post('submit', 'CheckoutController@submit')->name('submit');
});

html/app/User.php
<?php

namespace App;

class User extends \Konekt\AppShell\Models\User
{
}

html/app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Vanilo\Cart\Contracts\CartItem;
use Vanilo\Cart\Facades\Cart;
use Vanilo\Product\Contracts\Product;

class CartController extends Controller
{
    public function add(Product $product)
    {
        Cart::addItem($product);
        flash()->success($product->name . ' has been added to cart');

        return redirect()->route('cart.show');
    }

    public function remove(CartItem $cart_item)
    {
        Cart::removeItem($cart_item);
        flash()->info($cart_item->getBuyable()->getName() . ' has been removed from cart');

        return redirect()->route('cart.show');
    }

    public function update(CartItem $cart_item, Request $request)
    {
        $qty = (int) $request->get('qty', $cart_item->getQuantity());
        $cart_item->quantity = $qty;
        $cart_item->save();

        flash()->info($cart_item->getBuyable()->getName() . ' has been updated');

        return redirect()->route('cart.show');
    }

    public function show()
    {
        return view('cart.show');
    }
}

html/app/Http/Controllers/CheckoutController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests\CheckoutRequest;
use Konekt\Address\Models\CountryProxy;
use Vanilo\Cart\Facades\Cart;
use Vanilo\Checkout\Facades\Checkout;
use Vanilo\Order\Contracts\OrderFactory;

class CheckoutController extends Controller
{
    public function show()
    {
        $checkout = false;

        if (Cart::isNotEmpty()) {
            $checkout = Checkout::getFacadeRoot();
            if ($old = old()) {
                $checkout->update($old);
            }

            $checkout->setCart(Cart::model());
        }

        return view('checkout.show', [
            'checkout'  => $checkout,
            'countries' => CountryProxy::all()
        ]);
    }

    public function submit(CheckoutRequest $request, OrderFactory $orderFactory)
    {
        $checkout = Checkout::getFacadeRoot();
        $checkout->update($request->all());
        $checkout->setCart(Cart::model());

        $order = $orderFactory->createFromCheckout($checkout);
        Cart::destroy();

        return view('checkout.thankyou', ['order' => $order]);
    }

}

html/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

html/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

html/app/Http/Controllers/ShopController.php
<?php

namespace App\Http\Controllers;

use Vanilo\Category\Contracts\Taxon;
use Vanilo\Category\Models\TaxonomyProxy;
use Vanilo\Product\Contracts\Product;
use Vanilo\Product\Models\ProductProxy;

class ShopController extends Controller
{
    public function index()
    {
        $taxonomies = TaxonomyProxy::get();

        return view('shop.index', [
            'products' => ProductProxy::actives()->get(),
            'taxonomies' => $taxonomies,
            'taxon' => null
        ]);
    }

    public function category(string $taxonomyName, Taxon $taxon)
    {
        $taxonomies = TaxonomyProxy::get();

        return view('shop.index', [
            'products' => $taxon->products()->actives()->get(),
            'taxonomies' => $taxonomies,
            'taxon' => $taxon
        ]);
    }

    public function product(Product $product)
    {
        return view('shop.product', ['product' => $product]);
    }
}

html/resources/views/cart/_summary.blade.php
<table class="table table-borderless table-condensed">
    <tr>
        <th class="pl-0">Products:</th>
        <td>{{ format_price(Cart::total()) }}</td>
    </tr>
</table>

<h5>Total:</h5>
<h3>{{ format_price(Cart::total()) }}</h3>

<hr>

html/resources/views/cart/show.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('shop.index') }}">Shop Home</a></li>
    <li class="breadcrumb-item">Cart</li>
@stop

@section('content')
    <style>
        .product-image {
            height: 45px;
        }
    </style>
    <div class="container">
        <h1>Shopping Cart</h1>
        <hr>

        @if(Cart::isEmpty())
            <div class="alert alert-info">
                Your cart is empty
            </div>
        @else
        <div class="row">
            <div class="col-md-8">
                <div class="card bg-light">
                    <div class="card-header">Items</div>

                    <div class="card-body">
                        <div class="rounded bg-white">
                            <table class="table table-borderless">
                                <thead>
                                <tr>
                                    <th colspan="2">Name</th>
                                    <th>Price</th>
                                    <th>Qty</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach(Cart::getItems() as $item)
                                    <tr>
                                        <td width="55"><img src="{{ $item->product->getThumbnailUrl() ?: '/images/product.jpg' }}" class="product-image"/></td>
                                        <td>
                                            <a href="{{ route('shop.product', $item->product) }}">
                                                {{ $item->product->getName() }}
                                            </a></td>
                                        <td>{{ format_price($item->price) }}</td>
                                        <td>
                                            <form class="form-inline" action="{{ route('cart.update', $item) }}" method="POST">
                                                @csrf
                                                <input type="text" name="qty" value="{{ $item->quantity }}" class="w-25" />
                                            </form>
                                        </td>
                                        <td>{{ format_price($item->total) }}</td>
                                        <td>
                                            <form action="{{ route('cart.remove', $item) }}"
                                                  style="display: inline-block" method="post">
                                                {{ csrf_field() }}
                                                <button dusk="cart-delete-{{ $item->getBuyable()->id }}" class="btn btn-link btn-sm"><span class="text-danger">&xotime;</span></button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th colspan="4"></th>
                                    <th>
                                        {{ format_price(Cart::total()) }}
                                    </th>
                                    <th></th>
                                </tr>
                                </tfoot>

                            </table>
                        </div>

                        <p>
                            <a href="{{ route('shop.index') }}" class="btn-lg pl-0">Continue Shopping</a>
                        </p>

                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card bg-white">
                    <div class="card-header">Summary</div>
                    <div class="card-body">
                        @include('cart._summary')
                        <a href="{{ route('checkout.show') }}" class="btn btn-block btn-primary">Proceed To Checkout</a>
                    </div>
                </div>
            </div>
        </div>
        @endif
    </div>
@endsection

html/resources/views/checkout/_billing_address.blade.php
<h3>Billing Address</h3>
<hr>

<div class="form-group row">
    <label class="col-form-label col-md-2">{{ __('Country') }}</label>
    <div class="col-md-10">
        {{ Form::select('billpayer[address][country_id]', $countries->pluck('name', 'id'),
                setting('appshell.default.country'), [
                'class' => 'form-control' . ($errors->has('billpayer.address.country_id') ? ' is-invalid' : '')
            ])
        }}

        @if ($errors->has('billpayer.address.country_id'))
            <div class="invalid-feedback">{{ $errors->first('billpayer.address.country_id') }}</div>
        @endif
    </div>
</div>

<div class="form-group row">

    <label class="col-form-label col-md-2">{{ __('Address') }}</label>
    <div class="col-md-10">
        {{ Form::text('billpayer[address][address]', null, [
                'class' => 'form-control' . ($errors->has('billpayer.address.address') ? ' is-invalid' : '')
            ])
        }}
        @if ($errors->has('billpayer.address.address'))
            <div class="invalid-feedback">{{ $errors->first('billpayer.address.address') }}</div>
        @endif
    </div>
</div>

<div class="form-group row">

    <label class="col-form-label col-md-2">{{ __('Zip code') }}</label>
    <div class="col-md-4">
        {{ Form::text('billpayer[address][postalcode]', null, [
                'class' => 'form-control' . ($errors->has('billpayer.address.postalcode') ? ' is-invalid' : '')
            ])
        }}
        @if ($errors->has('billpayer.address.postalcode'))
            <div class="invalid-feedback">{{ $errors->first('billpayer.address.postalcode') }}</div>
        @endif
    </div>

    <label class="col-form-label col-md-2">{{ __('City') }}</label>
    <div class="col-md-4">
        {{ Form::text('billpayer[address][city]', null, [
                'class' => 'form-control' . ($errors->has('billpayer.address.city') ? ' is-invalid' : '')
            ])
        }}
        @if ($errors->has('billpayer.address.city'))
            <div class="invalid-feedback">{{ $errors->first('billpayer.address.city') }}</div>
        @endif
    </div>

</div>

html/resources/views/checkout/_billpayer.blade.php
<h3>Bill To</h3>
<hr>

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {{ Form::text('billpayer[firstname]', null, [
                    'class' => 'form-control' . ($errors->has('billpayer.firstname') ? ' is-invalid' : ''),
                    'placeholder' => __('First name')
                ])
            }}

            @if ($errors->has('billpayer.firstname'))
                <div class="invalid-feedback">{{ $errors->first('billpayer.firstname') }}</div>
            @endif
        </div>
    </div>

    <div class="col-md-6">
        <div class="form-group">
            {{ Form::text('billpayer[lastname]', null, [
                    'class' => 'form-control' . ($errors->has('billpayer.lastname') ? ' is-invalid' : ''),
                    'placeholder' => __('Last name')
                ])
            }}

            @if ($errors->has('billpayer.lastname'))
                <div class="invalid-feedback">{{ $errors->first('billpayer.lastname') }}</div>
            @endif
        </div>
    </div>

</div>


<div class="form-group">
    <div class="form-check">
        <input class="form-check-input" id="chk_is_organization" type="checkbox"
               name="billpayer[is_organization]" value="1" v-model="isOrganization">
        <label class="form-check-label" for="chk_is_organization">{{ __('Bill to Company') }}</label>
    </div>
</div>

<div id="billpayer-organization" v-show="isOrganization">
    <div class="form-group">
        {{ Form::text('billpayer[company_name]', null, [
                'class' => 'form-control form-control-lg' . ($errors->has('billpayer.company_name') ? ' is-invalid' : ''),
                'placeholder' => __('Company name')
             ])
        }}
        @if ($errors->has('billpayer.company_name'))
            <div class="invalid-feedback">{{ $errors->first('billpayer.company_name') }}</div>
        @endif
    </div>

    <div class="form-group">
        {{ Form::text('billpayer[tax_nr]', null, [
                'class' => 'form-control' . ($errors->has('billpayer.tax_nr') ? ' is-invalid' : ''),
                'placeholder' => __('Tax no.')
            ])
        }}
        @if ($errors->has('billpayer.tax_nr'))
            <div class="invalid-feedback">{{ $errors->first('billpayer.tax_nr') }}</div>
        @endif
    </div>
</div>

@include('checkout._billing_address', ['address' => $billpayer->getBillingAddress()])

html/resources/views/checkout/_shipping_address.blade.php
<div id="shipping-address" v-show="!shipToBillingAddress">
    <h3>Shipping Address</h3>
    <hr>

    <div class="form-group row">

        <label class="col-form-label col-md-2">{{ __('Name') }}</label>
        <div class="col-md-10">
            {{ Form::text('shippingAddress[name]', null, [
                    'class' => 'form-control' . ($errors->has('shippingAddress.name') ? ' is-invalid' : '')
                ])
            }}
            @if ($errors->has('shippingAddress.name'))
                <div class="invalid-feedback">{{ $errors->first('shippingAddress.name') }}</div>
            @endif
        </div>
    </div>

    <div class="form-group row">
        <label class="col-form-label col-md-2">{{ __('Country') }}</label>
        <div class="col-md-10">
            {{ Form::select('shippingAddress[country_id]', $countries->pluck('name', 'id'),
                    setting('appshell.default.country'), [
                    'class' => 'form-control' . ($errors->has('shippingAddress.country_id') ? ' is-invalid' : '')
                ])
            }}
            @if ($errors->has('shippingAddress.country_id'))
                <div class="invalid-feedback">{{ $errors->first('shippingAddress.country_id') }}</div>
            @endif
        </div>
    </div>

    <div class="form-group row">

        <label class="col-form-label col-md-2">{{ __('Address') }}</label>
        <div class="col-md-10">
            {{ Form::text('shippingAddress[address]', null, [
                    'class' => 'form-control' . ($errors->has('shippingAddress.address') ? ' is-invalid' : '')
                ])
            }}
            @if ($errors->has('shippingAddress.address'))
                <div class="invalid-feedback">{{ $errors->first('shippingAddress.address') }}</div>
            @endif
        </div>
    </div>

    <div class="form-group row">

        <label class="col-form-label col-md-2">{{ __('Zip code') }}</label>
        <div class="col-md-4">
            {{ Form::text('shippingAddress[postalcode]', null, [
                    'class' => 'form-control' . ($errors->has('shippingAddress.postalcode') ? ' is-invalid' : '')
                ])
            }}
            @if ($errors->has('shippingAddress.postalcode'))
                <div class="invalid-feedback">{{ $errors->first('shippingAddress.postalcode') }}</div>
            @endif
        </div>

        <label class="col-form-label col-md-2">{{ __('City') }}</label>
        <div class="col-md-4">
            {{ Form::text('shippingAddress[city]', null, [
                    'class' => 'form-control' . ($errors->has('shippingAddress.city') ? ' is-invalid' : '')
                ])
            }}
            @if ($errors->has('shippingAddress.city'))
                <div class="invalid-feedback">{{ $errors->first('shippingAddress.city') }}</div>
            @endif
        </div>

    </div>
</div>

html/resources/views/checkout/show.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('shop.index') }}">Shop Home</a></li>
    <li class="breadcrumb-item"><a href="{{ route('cart.show') }}">Cart</a></li>
    <li class="breadcrumb-item">Checkout</li>

@stop

@section('content')
    <style>
        .product-image {
            max-width: 100%;
            display: block;
            margin-bottom: 2em;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Checkout</div>

                    <div class="card-body">
                        @unless ($checkout)
                            <div class="alert alert-warning">
                                <p>Hey, nothing to check out here!</p>
                            </div>
                        @endunless

                        @if ($checkout)
                            <form id="checkout" action="{{ route('checkout.submit') }}" method="post">
                                {{ csrf_field() }}

                                @include('checkout._billpayer', ['billpayer' => $checkout->getBillPayer()])

                                <div class="mb-4">
                                    <input type="hidden" name="ship_to_billing_address" value="0" />
                                    <div class="form-check">
                                        <input class="form-check-input" id="chk_ship_to_billing_address" type="checkbox" name="ship_to_billing_address" value="1" v-model="shipToBillingAddress">
                                        <label class="form-check-label" for="chk_ship_to_billing_address">Ship to the same address</label>
                                    </div>
                                </div>

                                @include('checkout._shipping_address', ['address' => $checkout->getShippingAddress()])

                                <hr>

                                <div>
                                    <button class="btn btn-lg btn-success">Submit Order</button>
                                </div>


                            </form>
                        @endif
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-white">
                    <div class="card-header">Summary</div>
                    <div class="card-body">
                        @include('cart._summary')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @if ($checkout)
    <script>
        document.addEventListener("DOMContentLoaded", function(event) {
            new Vue({
                el: '#checkout',
                data: {
                    isOrganization: {{ old('billpayer.is_organization') ?: 0 }},
                    shipToBillingAddress: {{ old('ship_to_billing_address') ?? 1 }}
                }
            });
        });
    </script>
    @endif
@stop

html/resources/views/checkout/thankyou.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('shop.index') }}">Shop Home</a></li>
    <li class="breadcrumb-item"><a href="{{ route('cart.show') }}">Cart</a></li>
    <li class="breadcrumb-item">Checkout</li>
    <li class="breadcrumb-item">Order Complete</li>

@stop

@section('content')
    <div class="container">
        <h1>Wonderful {{ $order->getBillpayer()->firstname }}!</h1>
        <hr>

        <div class="alert alert-success">Your order has been registered with number
            <strong>{{ $order->getNumber() }}</strong>.
        </div>

        <h3>Next Steps</h3>

        <ol>
            <li>Your order will be prepared in the next 24 hours.</li>
            <li>Your package will be handed over to the courier.</li>
            <li>You'll receive an E-mail with the Shipment Information.</li>
        </ol>

        <div>
            <a href="{{ route('shop.index') }}" class="btn btn-info">All right!</a>
        </div>

    </div>
@endsection

html/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

html/resources/views/layouts/_favicons.blade.php
<link rel="shortcut icon" href="/favicon.ico">
<link rel="icon" sizes="16x16 32x32 64x64" href="/favicon.ico">
<link rel="icon" type="image/png" sizes="196x196" href="/favicons/favicon-192.png">
<link rel="icon" type="image/png" sizes="160x160" href="/favicons/favicon-160.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicons/favicon-96.png">
<link rel="icon" type="image/png" sizes="64x64" href="/favicons/favicon-64.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16.png">
<link rel="apple-touch-icon" href="/favicons/favicon-57.png">
<link rel="apple-touch-icon" sizes="114x114" href="/favicons/favicon-114.png">
<link rel="apple-touch-icon" sizes="72x72" href="/favicons/favicon-72.png">
<link rel="apple-touch-icon" sizes="144x144" href="/favicons/favicon-144.png">
<link rel="apple-touch-icon" sizes="60x60" href="/favicons/favicon-60.png">
<link rel="apple-touch-icon" sizes="120x120" href="/favicons/favicon-120.png">
<link rel="apple-touch-icon" sizes="76x76" href="/favicons/favicon-76.png">
<link rel="apple-touch-icon" sizes="152x152" href="/favicons/favicon-152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/favicons/favicon-180.png">
<meta name="msapplication-TileColor" content="#FFFFFF">
<meta name="msapplication-TileImage" content="/favicons/favicon-144.png">
<meta name="msapplication-config" content="/browserconfig.xml">

html/resources/views/shop/_breadcrumbs.blade.php
<?php
    $stack = [];
    $stack[] = [
        'url'   => route('shop.category', [$taxon->taxonomy->slug, $taxon]),
        'label' => $taxon->name
    ];

    $parent = $taxon;
    while ($parent = $parent->parent) {
        $stack[] = [
            'url'   => route('shop.category', [$parent->taxonomy->slug, $parent]),
            'label' => $parent->name
        ];
    }
    $stack[] = [
        'url'   => '#',
        'label' => $taxon->taxonomy->name
    ]
?>
@foreach(array_reverse($stack) as $item)
    <li class="breadcrumb-item"><a href="{{ $item['url'] }}">{{ $item['label'] }}</a></li>
@endforeach

html/resources/views/shop/_category.blade.php
<article class="card shadow-sm">
    <div class="card-body">
        <h5><a href="{{ route('shop.category', [$taxon->taxonomy->name, $taxon]) }}">{{ $taxon->name }}</a></h5>
    </div>
</article>

html/resources/views/shop/_category_level.blade.php
@foreach($taxons as $taxon)
<div>
    @if($taxon->children->count())

        <div class="btn-group dropright">
            <a href="{{ route('shop.category', [$taxon->taxonomy->slug, $taxon]) }}" class="btn btn-link">
                {{ $taxon->name }}
            </a>
            <button type="button" class="btn btn-link dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropright</span>
            </button>
            <div class="dropdown-menu">
                @foreach($taxon->children as $child)
                    <a class="dropdown-item" href="{{ route('shop.category', [$child->taxonomy->slug, $child]) }}">{{ $child->name }}</a>
                @endforeach
            </div>
        </div>
    @else
        <a class="btn btn-link" href="{{ route('shop.category', [$taxon->taxonomy->slug, $taxon]) }}">{{ $taxon->name }}</a>
    @endif
</div>
@endforeach

html/resources/views/shop/_product.blade.php
<article class="card shadow-sm">
    <a href="{{ route('shop.product', $product) }}">
        <img class="card-img-top"
        @if($product->hasImage())
            src="{{ $product->getThumbnailUrl() }}"
        @else
            src="/images/product.jpg"
        @endif
        alt="{{ $product->name }}" />
    </a>

    <div class="card-body">
        <h5><a href="{{ route('shop.product', $product) }}">{{ $product->name }}</a></h5>
        <p class="card-text">{{ format_price($product->price) }}</p>
    </div>
</article>

html/resources/views/shop/index.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('shop.index') }}">Shop Home</a></li>
    @if($taxon)
        @include('shop._breadcrumbs')
    @endif
@stop

@section('content')
    <div class="container">
        <div class="row">

            <div class="col-md-4">
                @foreach($taxonomies as $taxonomy)
                <div class="card card-default mb-3">
                    <div class="card-header">{{ $taxonomy->name }}</div>
                    <div class="card-body">
                        @include('shop._category_level', ['taxons' => $taxonomy->rootLevelTaxons()])
                    </div>
                </div>
                @endforeach
            </div>

            <div class="col-md-8">
                @if($taxon && $products->isEmpty() && $taxon->children->count())
                    <div class="card card-default mb-4">
                        <div class="card-header">{{ $taxon->name }} Subcategories</div>

                        <div class="card-body">
                            <div class="row">
                            @foreach($taxon->children as $child)
                                <div class="col-12 col-sm-6 col-md-4 mb-4">
                                    @include('shop._category', ['taxon' => $child])
                                </div>
                            @endforeach
                            </div>
                        </div>
                    </div>
                @endif

                @if(!$products->isEmpty())
                <div class="card card-default">
                    <div class="card-header">{{ $taxon ?  'Products in ' . $taxon->name : 'All Products' }}</div>

                    <div class="card-body">
                        <div class="row">

                            @foreach($products as $product)
                                <div class="col-12 col-sm-6 col-md-4 mb-4">
                                    @include('shop._product')
                                </div>
                            @endforeach

                        </div>
                    </div>
                </div>
                @endif
            </div>
        </div>
    </div>
@endsection

html/resources/views/shop/product.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('shop.index') }}">Shop Home</a></li>
    @if ($product->taxons->count())
        @include('shop._breadcrumbs', ['taxon' => $product->taxons->first()])
    @endif
    <li class="breadcrumb-item">{{ $product->name }}</li>
@stop

@section('content')
    <style>
        .thumbnail-container {
            overflow-x: scroll;
        }

        .thumbnail {
            width: 64px;
            height: auto;
            display: block;
            float: left;
        }

        .thumbnail img {
            cursor: pointer;
        }
    </style>
    <div class="container">
        <h1>{{ $product->name }}</h1>
        <hr>

        <div class="row">
            <div class="col-md-6">
                <div class="mb-2">
                    <?php $img = $product->getMedia()->first() ? $product->getMedia()->first()->getUrl('medium') : '/images/product-medium.jpg' ?>
                    <img src="{{ $img  }}" id="product-image" />
                </div>

                <div class="thumbnail-container">
                    @foreach($product->getMedia() as $media)
                        <div class="thumbnail mr-1">
                            <img class="mw-100" src="{{ $media->getUrl('thumbnail') }}"
                                 onclick="document.getElementById('product-image').setAttribute('src', '{{ $media->getUrl("medium") }}')"
                            />
                        </div>
                    @endforeach
                </div>
            </div>

            <div class="col-md-6">
                <form action="{{ route('cart.add', $product) }}" method="post" class="mb-4">
                    {{ csrf_field() }}

                    <span class="mr-2 font-weight-bold text-primary btn-lg">{{ format_price($product->price) }}</span>
                    <button type="submit" class="btn btn-success btn-lg" @if(!$product->price) disabled @endif>Add to cart</button>
                </form>

                <hr>

                <p class="text-secondary">{!!  nl2br($product->description) !!}</p>

                <hr>

            </div>
        </div>
    </div>
@endsection